# Generated by Django 5.0.4 on 2024-04-19 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upc', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=50, null=True)),
                ('description', models.TextField(null=True)),
                ('stock', models.IntegerField(default=0)),
                ('price', models.FloatField()),
                ('tax', models.FloatField(default=0)),
                ('rating', models.FloatField(default=5.0)),
                ('reviews', models.IntegerField()),
            ],
        ),
    ]
