# Generated by Django 5.0.4 on 2024-04-19 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(db_column='category', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(db_column='description', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(db_column='name', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(db_column='price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.FloatField(db_column='rating', default=5.0),
        ),
        migrations.AlterField(
            model_name='product',
            name='reviews',
            field=models.IntegerField(db_column='reviews'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(db_column='stock', default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='tax',
            field=models.FloatField(db_column='tax', default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(db_column='type', max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='upc',
            field=models.CharField(db_column='upc', max_length=255),
        ),
    ]
