# Generated by Django 5.0.4 on 2024-04-19 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_product_category_alter_product_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='upc',
            field=models.CharField(db_column='upc', help_text='univercel product code', max_length=255),
        ),
    ]
